name=input("name")
branch=input("branch")
gender=input("gender")
collegename=input("college name")
age=input("age")
print("name:",name)
print("branch:",branch) 
print("gender:",gender) 
print("collegename:",collegename) 
print("age:",age) 
